# Open Peer Review

Portfolio assignment 1.2
<hr />

This assignment is about identifying reproducibility issues in a scientific publication. Therefor we must use the criteria cited in table 1.

Table 1. Repita Criteria as given in Portfolio [Assignment 1.2](https://lesmaterialen.rstudio.hu.nl/workflows-reader/represintro.html)

| Transparency Criteria| Definition       | Response Type|
|---------|-------------------------------|----------|
|Study Purpose |A concise statement in the introduction of the article, often in the last paragraph, that establishes the reason the research was conducted. Also called the study objective.| Binary| 
|Data Availability Statement | A statement, in an individual section offset from the main body of text, that explains how or if one can access a study’s data. The title of the section may vary, but it must explicitly mention data; it is therefore distinct from a supplementary materials section.| Binary|
|Data Location | Where the article’s data can be accessed, either raw or processed.| Found Value|
|Study Location| Author has stated in the methods section where the study took place or the data’s country/region of origin.| Binary; Found Value|
|Author Review| The professionalism of the contact information that the author has provided in the manuscript.|Found Value|
|Ethics Statement | A statement within the manuscript indicating any ethical concerns, including the presence of sensitive data.|Binary|
|Funding Statement| A statement within the manuscript indicating whether or not the authors received funding for their research.|Binary|
Code Availability | Authors have shared access to the most updated code that they used in their study, including code used for analysis. |Binary|

Part 1:
<br/>
https://pubmed.ncbi.nlm.nih.gov/32931516/
<br/>
The article I found was published September 15th, 2020.
[DOI:10.1371/journal.pcbi.1008182](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008182)
<br/>
Article: MONET: Multi-omic module discovery by omic selection
<br/>
Autors: Nimrod Rappoport, Roy Safra, Ron Shamir 


| Transparency Criteria| Response  | Explanation|
|---------|-----------|----------|
|Study Purpose |1| It was not easy to find but the idea is that when you so omics, you only look at one omic. But you can look at multiple omics with one sample to get a better picture on something. In this case cancer.| 
|Data Availability Statement | 01| Binary|
|Data Location | 01| Found Value|
|Study Location| 01| Binary; Found Value|
|Author Review| 01|Found Value|
|Ethics Statement | 01|Binary|
|Funding Statement| 01|Binary|
|Code Availability | 01 |Binary|